const recipes=[
{id:1,title:"Macarrão cremoso",category:"Jantar",emoji:"🍝",time:"25 min",servings:"2 pessoas",difficulty:"Fácil",description:"Macarrão cremoso, rápido e perfeito para um jantar simples.",ingredients:["250 g de macarrão","1 colher de manteiga","1/2 cebola","1 caixa de creme de leite","50 g de queijo ralado","Sal e pimenta"],steps:["Cozinhe o macarrão e reserve um pouco da água.","Refogue a cebola na manteiga.","Adicione creme de leite, queijo e temperos em fogo baixo.","Junte o macarrão e um pouco da água reservada.","Misture até ficar cremoso e sirva."]},
{id:2,title:"Frango grelhado",category:"Almoço",emoji:"🍗",time:"30 min",servings:"2 pessoas",difficulty:"Fácil",description:"Frango dourado para acompanhar arroz, salada ou legumes.",ingredients:["2 filés de frango","1 dente de alho","1 colher de azeite","1/2 limão","Sal, páprica e pimenta"],steps:["Tempere o frango.","Aqueça uma frigideira com azeite.","Grelhe os filés dos dois lados.","Verifique se estão completamente cozidos.","Sirva com acompanhamentos."]},
{id:3,title:"Brigadeiro",category:"Sobremesa",emoji:"🍫",time:"20 min",servings:"15 unidades",difficulty:"Fácil",description:"Clássico brigadeiro para festas ou para adoçar o dia.",ingredients:["1 lata de leite condensado","1 colher de manteiga","3 colheres de chocolate em pó","Granulado"],steps:["Misture leite condensado, manteiga e chocolate.","Cozinhe em fogo baixo mexendo sempre.","Quando engrossar, desligue.","Espere esfriar.","Enrole e passe no granulado."]},
{id:4,title:"Panqueca de banana",category:"Café da manhã",emoji:"🥞",time:"15 min",servings:"1 pessoa",difficulty:"Fácil",description:"Panquecas rápidas e deliciosas para começar o dia.",ingredients:["1 banana","1 ovo","3 colheres de aveia","Canela"],steps:["Amasse a banana.","Misture ovo, aveia e canela.","Aqueça uma frigideira levemente untada.","Coloque porções da massa.","Doure os dois lados."]},
{id:5,title:"Sanduíche especial",category:"Lanche",emoji:"🥪",time:"10 min",servings:"1 pessoa",difficulty:"Fácil",description:"Lanche rápido para qualquer hora.",ingredients:["2 fatias de pão","Queijo","Presunto ou frango","Tomate","Alface","Molho"],steps:["Passe o molho no pão.","Monte os ingredientes.","Feche o sanduíche.","Aqueça se quiser.","Sirva."]},
{id:6,title:"Arroz de forno",category:"Almoço",emoji:"🍚",time:"40 min",servings:"4 pessoas",difficulty:"Médio",description:"Uma ótima forma de transformar arroz pronto em refeição.",ingredients:["3 xícaras de arroz cozido","1 xícara de frango","Milho","Ervilha","200 g de queijo","Molho de tomate"],steps:["Misture arroz, frango, milho, ervilha e molho.","Coloque em uma travessa.","Cubra com queijo.","Leve ao forno até gratinar.","Sirva com cuidado."]}
];
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
let currentRecipe=null,currentRating=0;
const users=()=>JSON.parse(localStorage.getItem("sp_users")||"[]");
const saveUsers=x=>localStorage.setItem("sp_users",JSON.stringify(x));
const session=()=>JSON.parse(localStorage.getItem("sp_session")||"null");
function reviews(){return JSON.parse(localStorage.getItem("sp_reviews")||"{}")}
function saveReviews(x){localStorage.setItem("sp_reviews",JSON.stringify(x))}
function favorites(){return JSON.parse(localStorage.getItem("sp_favorites")||"[]")}
function saveFavorites(x){localStorage.setItem("sp_favorites",JSON.stringify(x))}
function showApp(){$("#authScreen").classList.add("hidden");$("#app").classList.remove("hidden");$("#userName").textContent="Olá, "+session().name;renderAll()}
function showAuth(){$("#authScreen").classList.remove("hidden");$("#app").classList.add("hidden")}
function msg(id,t,ok=false){$(id).textContent=t;$(id).style.color=ok?"#2d8a52":"#c6422a"}
$$(".auth-tab").forEach(b=>b.onclick=()=>{$$(".auth-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");let l=b.dataset.tab==="login";$("#loginForm").classList.toggle("hidden",!l);$("#registerForm").classList.toggle("hidden",l)});
$("#registerForm").onsubmit=e=>{e.preventDefault();let name=$("#registerName").value.trim(),email=$("#registerEmail").value.trim().toLowerCase(),password=$("#registerPassword").value;if(password!==$("#registerConfirm").value)return msg("#registerMessage","As senhas não são iguais.");let u=users();if(u.some(x=>x.email===email))return msg("#registerMessage","Este e-mail já está cadastrado.");u.push({name,email,password});saveUsers(u);msg("#registerMessage","Conta criada! Agora entre.",true);setTimeout(()=>{$('[data-tab="login"]').click();$("#loginEmail").value=email},600)};
$("#loginForm").onsubmit=e=>{e.preventDefault();let email=$("#loginEmail").value.trim().toLowerCase(),password=$("#loginPassword").value,u=users().find(x=>x.email===email&&x.password===password);if(!u)return msg("#loginMessage","E-mail ou senha incorretos.");localStorage.setItem("sp_session",JSON.stringify({name:u.name,email:u.email}));showApp()};
$("#logoutBtn").onclick=()=>{localStorage.removeItem("sp_session");showAuth()};
function avg(id){let r=reviews()[id]||[];return r.length?r.reduce((a,x)=>a+x.rating,0)/r.length:0}
function stars(n){return "★★★★★".split("").map((s,i)=>i<n?"★":"☆").join("")}
function card(r){let fav=favorites().includes(r.id);return `<article class="recipe-card"><div class="recipe-image">${r.emoji}</div><div class="recipe-body"><button class="favorite-mini" data-fav="${r.id}">${fav?"❤️":"♡"}</button><span class="tag">${r.category}</span><h3>${r.title}</h3><p>${r.description}</p><div class="meta"><span>⏱ ${r.time}</span><span>⭐ ${avg(r.id).toFixed(1)}</span></div><button class="view-btn" data-id="${r.id}">Ver receita completa</button></div></article>`}
function renderRecipes(){let q=$("#searchInput").value.toLowerCase(),cat=$(".filter.active")?.dataset.category||"Todas";let a=recipes.filter(r=>(cat==="Todas"||r.category===cat)&&(r.title+" "+r.description+" "+r.category).toLowerCase().includes(q));$("#recipeGrid").innerHTML=a.map(card).join("");$("#emptyState").classList.toggle("hidden",a.length>0);bindCards()}
function renderFavorites(){let f=recipes.filter(r=>favorites().includes(r.id));$("#favoriteGrid").innerHTML=f.map(card).join("");$("#favoriteEmpty").classList.toggle("hidden",f.length>0);bindCards()}
function renderRanking(){let a=[...recipes].sort((x,y)=>avg(y.id)-avg(x.id));$("#rankingGrid").innerHTML=a.slice(0,3).map((r,i)=>`<div class="rank-card"><div class="rank-num">#${i+1}</div><div class="rank-emoji">${r.emoji}</div><div><strong>${r.title}</strong><div class="stars">${stars(Math.round(avg(r.id)))}</div><small>${avg(r.id).toFixed(1)} / 5</small></div></div>`).join("")}
function renderAll(){renderRecipes();renderFavorites();renderRanking()}
function bindCards(){$$(".view-btn").forEach(b=>b.onclick=()=>openRecipe(+b.dataset.id));$$("[data-fav]").forEach(b=>b.onclick=()=>{let id=+b.dataset.fav,f=favorites();f=f.includes(id)?f.filter(x=>x!==id):[...f,id];saveFavorites(f);renderAll()})}
$$(".filter").forEach(b=>b.onclick=()=>{$$(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderRecipes()});
$("#searchInput").oninput=renderRecipes;
function openRecipe(id){currentRecipe=recipes.find(r=>r.id===id);currentRating=0;$("#modalEmoji").textContent=currentRecipe.emoji;$("#modalCategory").textContent=currentRecipe.category;$("#modalTitle").textContent=currentRecipe.title;$("#modalDescription").textContent=currentRecipe.description;$("#modalTime").textContent=currentRecipe.time;$("#modalServings").textContent=currentRecipe.servings;$("#modalDifficulty").textContent=currentRecipe.difficulty;$("#modalIngredients").innerHTML=currentRecipe.ingredients.map(x=>`<li>${x}</li>`).join("");$("#modalSteps").innerHTML=currentRecipe.steps.map(x=>`<li>${x}</li>`).join("");$("#favoriteBtn").textContent=favorites().includes(id)?"❤️ Remover favorito":"♡ Favoritar";drawStars();renderReviews();$("#recipeModal").classList.remove("hidden")}
function drawStars(){$("#starPicker").innerHTML=[1,2,3,4,5].map(n=>`<button class="star ${n<=currentRating?"selected":""}" data-star="${n}">★</button>`).join("");$$("[data-star]").forEach(b=>b.onclick=()=>{currentRating=+b.dataset.star;drawStars()})}
$("#favoriteBtn").onclick=()=>{let f=favorites();f=f.includes(currentRecipe.id)?f.filter(x=>x!==currentRecipe.id):[...f,currentRecipe.id];saveFavorites(f);$("#favoriteBtn").textContent=f.includes(currentRecipe.id)?"❤️ Remover favorito":"♡ Favoritar";renderAll()};
$("#shareBtn").onclick=async()=>{let text=`Confira a receita "${currentRecipe.title}" no Sabor & Panela!`;try{if(navigator.share)await navigator.share({title:currentRecipe.title,text,url:location.href});else{await navigator.clipboard.writeText(text+" "+location.href);msg("#reviewMessage","Link copiado para a área de transferência.",true)}}catch{}};
$("#reviewBtn").onclick=()=>{if(!currentRating)return msg("#reviewMessage","Escolha uma nota de 1 a 5 estrelas.");let text=$("#reviewText").value.trim(),all=reviews();all[currentRecipe.id]=all[currentRecipe.id]||[];all[currentRecipe.id].unshift({name:session().name,rating:currentRating,text,date:new Date().toLocaleDateString("pt-BR")});saveReviews(all);$("#reviewText").value="";$("#reviewMessage").textContent="Avaliação enviada!";$("#reviewMessage").style.color="#2d8a52";renderReviews();renderAll()};
function renderReviews(){let a=reviews()[currentRecipe.id]||[];$("#reviewsList").innerHTML=a.length?a.map(x=>`<div class="review-item"><div class="review-head"><strong>${escapeHtml(x.name)}</strong><span class="stars">${stars(x.rating)} • ${x.date}</span></div><p>${escapeHtml(x.text||"Sem comentário.")}</p></div>`).join(""):"<p class='empty'>Ainda não há avaliações. Seja o primeiro!</p>"}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
$$("[data-close]").forEach(x=>x.onclick=()=>$("#recipeModal").classList.add("hidden"));
document.addEventListener("keydown",e=>{if(e.key==="Escape")$("#recipeModal").classList.add("hidden")});
$("#menuBtn").onclick=()=>$("#navMenu").classList.toggle("open");
$$("nav a").forEach(a=>a.onclick=()=>$("#navMenu").classList.remove("open"));
if(session())showApp();else showAuth();
